# Generated by Django 3.2.19 on 2023-06-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0002_auto_20230618_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='man',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Популярные мужики', 'verbose_name_plural': 'Популярные мужики'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='man',
            name='content',
            field=models.TextField(blank=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='man',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
